CREATE TABLE VAR_CLIMA_INMET AS 
SELECT 
	 DT_MEDICAO
	,COD_ESTACAO
	,ESTACAO
	,LATITUDE
	,LONGITUDE
	,MAX(PRECIPITACAO_TOTAL_HORARIO_MM)+MIN(PRECIPITACAO_TOTAL_HORARIO_MM) AS PRECIPITACAO_IND
	,MAX(PRESSAO_ATMOSFERICA_AO_NIVEL_DA_ESTACAO_HORARIA_MB)+MIN(PRESSAO_ATMOSFERICA_AO_NIVEL_DA_ESTACAO_HORARIA_MB) AS PRESSAO_ATM_EST_IND
	,MAX("PRESSAO_ATMOSFERICA_REDUZIDA_NIVEL_MAR+AUT_MB")+MIN("PRESSAO_ATMOSFERICA_REDUZIDA_NIVEL_MAR+AUT_MB") AS PRESSAO_ATM_MAR_IND
	,MAX(RADIACAO_GLOBAL_KJM2)+MIN(RADIACAO_GLOBAL_KJM2) AS RADIACAO_GLOBAL_IND
	,MAX(TEMPERATURA_DO_AR_BULBO_SECO_HORARIA_C)+MIN(TEMPERATURA_DO_AR_BULBO_SECO_HORARIA_C) AS TEMPERATURA_DO_AR_BULBO_SECO_IND
	,MAX(TEMPERATURA_DO_PONTO_DE_ORVALHO_C)+MIN(TEMPERATURA_DO_PONTO_DE_ORVALHO_C) AS TEMPERATURA_DO_PONTO_DE_ORVALHO_IND
	,MAX(TEMPERATURA_MAXIMA_NA_HORA_ANT_AUT_C)+MIN(TEMPERATURA_MINIMA_NA_HORA_ANT_AUT_C) AS TEMPERATURA_IND
	,MAX(UMIDADE_RELATIVA_DO_AR_HORARIA_PERC)+MIN(UMIDADE_RELATIVA_DO_AR_HORARIA_PERC) AS UMIDADE_RELATIVA_IND
	,MAX(VENTO_RAJADA_MAXIMA_MS)+MIN(VENTO_RAJADA_MAXIMA_MS) AS VENTO_RAJADA_IND
	,MAX(VENTO_VELOCIDADE_HORARIA_MS)+MIN(VENTO_VELOCIDADE_HORARIA_MS) AS VENTO_VELOCIDADE_IND
FROM CLIMA_INMET 
GROUP BY 
	 DT_MEDICAO
	,COD_ESTACAO
	,ESTACAO
	,LATITUDE
	,LONGITUDE;


CREATE INDEX index_VAR_CLIMA_INMET
ON VAR_CLIMA_INMET
	(
	 DT_MEDICAO
	,COD_ESTACAO
	,ESTACAO
	,LATITUDE
	,LONGITUDE
	);